<?xml version="1.0"?>
<package format="3">
  <name>death_valley_world</name>
  <version>1.0.0</version>
  <description>Death Valley simulation environment for autonomous mobile robot navigation</description>
  <maintainer email="joshika@todo.todo">joshika</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ros_gz_sim</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
